services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doc_insight_service
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  gradio_ui:
    build:
      context: ./gradio_ui
      dockerfile: Dockerfile
    container_name: gradio_ui
    environment:
      DOC_INSIGHT_SERVICE_URL: http://backend:8000
    ports:
      - "7860:7860"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
